# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='poked_user',
        ),
        migrations.AddField(
            model_name='poke',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poked', to='login_app.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieved', to='login_app.User'),
        ),
    ]
