# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20170823_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='poke',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
