# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20170823_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='count',
        ),
        migrations.AddField(
            model_name='poke',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
